### PR TITLE
added auto recording of replays

### PR DESCRIPTION
**Pull request by Jaksuhn**
options to auto start/stop on duty start/end

changed replay files to be prefixed by the duty name (or zone name if that doesn't exist) instead of "World"
It also adds the appends the duty finder settings (unrestricted, level sync, min ilvl, no echo) as comma separated values after the instance name so `the Bowl of Embers_U,NE_2024_03_22_20_18_27.log` as an example

### CODE REVIEW

**Comment by McVaxius** [comment]
is it possible to disaggregate (just use random number for uuid + text for name)( player identifiable info for sharing replays?

**Comment by McVaxius** [comment]
merged and tested this PR this morning seems to be working fine for me

**Comment by McVaxius** [comment]
the final msq solo duty didnt auto stop recording when i left it also
(leaving when it was concluded in this case)

**Comment by Jaksuhn** [comment]
> found a bug with it
> 
> ran a sunken temple of qarn (normal one), then 20 minutes later queued into a zeromus and both got recorded. under the one qarn recording.
> 
> upon reviewing the replay. it seems like it never stopped recording.
> 
> i suspect its because i left the qarn 2/3 of the way through instead of completing it.

addressed

**Pull request merged**
