### PR TITLE
Bugfixes and improvements for the Tower of Zot modules

### PR DESCRIPTION
**Pull request by CarnifexOptimus**
based on PR #297
many bug fixes/improvements

not sure if everything is perfect now since testing is hard without multiboxing, but should be a lot better than before

### CODE REVIEW

**Comment by awgil** [comment]
Is it supposed to fully replace #297? Or am I expected to merge that PR first?

**Comment by CarnifexOptimus** [comment]
> Is it supposed to fully replace #297? Or am I expected to merge that PR first?

should fully replace it unless dhog has any objections

**Comment by McVaxius** [comment]
small problem with the 3rd boss arena w AI mode + spread per our discussion.

maybe disable the ai for donut for now idk.

**Comment by McVaxius** [comment]
> > Is it supposed to fully replace #297? Or am I expected to merge that PR first?
> 
> should fully replace it unless dhog has any objections

yeah of course. should i just close the other one?

**Pull request merged**
