### PR TITLE
modules for Ktisis Hyperboreia

### PR DESCRIPTION
**Pull request by xanunderscore**

### CODE REVIEW

**Comment by CarnifexOptimus** [comment]
can you even do any modules on your own? you pretty much copied everything that is remotely complicated from BMR again and made miniscule stylistic changes without giving credit

**Comment by adambennett55** [comment]
> can you even do any modules on your own? you pretty much copied everything that is remotely complicated from BMR again and made miniscule stylistic changes without giving credit
> 
> seems to be a general pattern for vbm users to spy at our work and copy and sell it as their own

Thats an odd comment, considering there is a set namingscheme for modules and the fight doesnt change no matter who write the module, ergo, they are gonna look nearly identical, cept for maybe some stylistic changes?

**Comment by CarnifexOptimus** [comment]
> > can you even do any modules on your own? you pretty much copied everything that is remotely complicated from BMR again and made miniscule stylistic changes without giving credit
> > seems to be a general pattern for vbm users to spy at our work and copy and sell it as their own
> 
> Thats an odd comment, considering there is a set namingscheme for modules and the fight doesnt change no matter who write the module, ergo, they are gonna look nearly identical, cept for maybe some stylistic changes?

not at all, there are a multitude of ways to solve problems

**Comment by adambennett55** [comment]
> > > can you even do any modules on your own? you pretty much copied everything that is remotely complicated from BMR again and made miniscule stylistic changes without giving credit
> > > seems to be a general pattern for vbm users to spy at our work and copy and sell it as their own
> > 
> > 
> > Thats an odd comment, considering there is a set namingscheme for modules and the fight doesnt change no matter who write the module, ergo, they are gonna look nearly identical, cept for maybe some stylistic changes?
> 
> not at all, there are a multitude of ways to solve problems

Example, please, because if there is a different way of doing something, then it brings into question, which is the "right" way? I believe modeling of the actual creator of the plugin itself would be the "right" way, and as such if 2 module creators did that, again they would look simliar, just my 2 cents

**Comment by adambennett55** [comment]
> > > can you even do any modules on your own? you pretty much copied everything that is remotely complicated from BMR again and made miniscule stylistic changes without giving credit
> > > seems to be a general pattern for vbm users to spy at our work and copy and sell it as their own
> > 
> > 
> > Thats an odd comment, considering there is a set namingscheme for modules and the fight doesnt change no matter who write the module, ergo, they are gonna look nearly identical, cept for maybe some stylistic changes?
> 
> not at all, there are a multitude of ways to solve problems. i don't have a problem if people copy, it's when they don't mention the origin where it becomes shady

I'm just saying, its bold to accuse someone of something without knowing 100% thats what happened, I would have talked to the person first, maybe asked if thats what he was doing? but thats just me

**Comment by CarnifexOptimus** [comment]
I am not blind, you can look at the code to see how similar it is.
It is also not the 1st time he does this.

**Comment by adambennett55** [comment]
> I am not blind, you can look at the code to see how similar it is. It is also not the 1st time he does this.

Listen, I am simply saying your approach wasn't perfect, and that there is a possibility that in a system like vbm that some things can look similar, I didn't say you were blind, hell I haven't even looked at either module, I just didn't like the way you came at it and I have a right to express my opinion on such. Sorry if it upset you.

**Comment by xanunderscore** [comment]
> you pretty much copied everything that is remotely complicated from BMR again and made miniscule stylistic changes without giving credit

there are three "complex" mechanics in the entire dungeon:

* lyssa's hide-and-seek aoe, the source of which you can calculate by adding a rotation + offset from the arena center, which is what i did - looks like BMR hardcodes the spawn points instead, which is fine because she can only spawn in 6 locations - if it was a more random mechanic this solution would be nonfunctional
* ladon lord's sequenced AOEs - i calculate which AOE is next by applying the inverse of whatever transformation is stored in his buff list, looks like BMR hardcodes all possible buff combinations - again, fine because he only does two AOEs in a row, but this would grow exponentially if he spawned more (like some A ranks do for example)
* hermes' meteor LoS thing - i computed the safe spots and then inverted them to build a forbidden zone so that AI can hide behind whatever meteor it wants - it looks like BMR just forces it to walk to the nearest unbroken meteor (CastLoSAOE doesn't build-in any AI hints? i thought you guys only cared about automation?)

IOW i didn't copy BMR's solution for any of these because all of the solutions in their modules are shit. all other information about boss mechanics is readily available from the replay file, which anyone can make just by using the plugin's record feature.

this type of repeated harassment in my PR comments is incredibly unprofessional and extremely embarrassing, not only for you but for the rest of the combatreborn team. please do not comment on my contributions in the future unless you have something useful to say. thanks.

**Pull request merged**
