### PR TITLE
ipc methods for preset creation

### PR DESCRIPTION
**Pull request by xanunderscore**

### CODE REVIEW

**Comment by adambennett55** [comment]
Could you possibly also add an IPC for setting the current preset for current class and getting the current preset for the current class

**Comment by awgil** [comment]
> Could you possibly also add an IPC for setting the current preset for current class and getting the current preset for the current class

I'm curious - why do you want different presets for different classes? The intention is to have 'situational' presets (eg single-target, aoe, etc), each of which has modules for all classes you care about.

**Comment by adambennett55** [comment]
> > Could you possibly also add an IPC for setting the current preset for current class and getting the current preset for the current class
> 
> I'm curious - why do you want different presets for different classes? The intention is to have 'situational' presets (eg single-target, aoe, etc), each of which has modules for all classes you care about.

well its not for different presets for different classes, AD would use the same preset for all but we just need the ability to set our preset as the AI preset, and to check if its already set to that, to turn Autorot on

**Comment by awgil** [comment]
Ah, so we need some extra IPC to modify AI preset then? And you can call this ipc after (re)importing AD preset.

**Comment by adambennett55** [comment]
yes exactly

**Comment by awgil** [comment]
Added AI.SetPreset IPC

**Pull request merged**
