### PR TITLE
Update for new dalamud

### PR DESCRIPTION
**Pull request by IncognitoWater**
I updated some declaration errors inside FloodFillTest.cs and modifed the applicable version for the current date. Idk if that's ok first time PR for this project. Just wanted to help ( F sorry i think i put some uncessary files with the fix, i removed them)

### CODE REVIEW

**Comment by SneakyBelg** [comment]
Any way to run the plugin without the PR getting merged? @IncognitoWater

**Comment by KHShadowrunner** [comment]
Build it yourself unfortunately.

**Comment by SneakyBelg** [comment]
Any easy way to do so?

**Comment by IncognitoWater** [comment]
I mean yeah you could build it however. I saw it perfectly working in some situation but also getting some errors too in some other raids we'll see maybe I did smth wrong or maybe it needs more update.

**Comment by awgil** [comment]
The version check is there for a reason - you also need to update network opcodes.

**Comment by awgil** [comment]
Update is now live.

**Pull request closed without merging**
